param(
  [Parameter(Mandatory = $true)]
  [string]$SourceMarkdown,

  [Parameter(Mandatory = $true)]
  [string]$Title,

  [string]$OutputPath = "Content.js"
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path -LiteralPath $SourceMarkdown)) {
  throw "Source markdown not found: $SourceMarkdown"
}

$content = Get-Content -LiteralPath $SourceMarkdown -Raw -Encoding UTF8
$payload = @{
  title = $Title
  markdown = $content
} | ConvertTo-Json -Depth 3

$js = @"
// Generated by build-content.ps1. Do not edit manually.
const CONTENT_PAYLOAD = $payload;
const CONTENT_TITLE = CONTENT_PAYLOAD.title;
const CONTENT_MD = CONTENT_PAYLOAD.markdown;
"@

Set-Content -LiteralPath $OutputPath -Value $js -Encoding UTF8
Write-Output "Generated $OutputPath from $SourceMarkdown"
